name: rustdfs-test

networks:
  rustdfs:
    driver: bridge

services:

  # ── data nodes ──────────────────────────────────────────────────────────────

  datanode0:
    build:
      context: ..
      dockerfile: test/Dockerfile.datanode
      args:
        DATANODE_HOST: datanode0
        DATANODE_PORT: "5001"
    hostname: datanode0
    environment:
      DATANODE_HOST: datanode0
      DATANODE_PORT: "5001"
    ports:
      - "5001:5001"
    networks:
      - rustdfs

  datanode1:
    build:
      context: ..
      dockerfile: test/Dockerfile.datanode
      args:
        DATANODE_HOST: datanode1
        DATANODE_PORT: "5002"
    hostname: datanode1
    environment:
      DATANODE_HOST: datanode1
      DATANODE_PORT: "5002"
    ports:
      - "5002:5002"
    networks:
      - rustdfs

  datanode2:
    build:
      context: ..
      dockerfile: test/Dockerfile.datanode
      args:
        DATANODE_HOST: datanode2
        DATANODE_PORT: "5003"
    hostname: datanode2
    environment:
      DATANODE_HOST: datanode2
      DATANODE_PORT: "5003"
    ports:
      - "5003:5003"
    networks:
      - rustdfs

  # ── name node ───────────────────────────────────────────────────────────────

  namenode:
    build:
      context: ..
      dockerfile: test/Dockerfile.namenode
    hostname: namenode
    ports:
      - "5000:5000"
    networks:
      - rustdfs
    depends_on:
      - datanode0
      - datanode1
      - datanode2
