replica-count = 2

[name-node]
host = "namenode"
port = 5000
name-file = "/var/lib/rustdfs/names"
log-file = "/var/log/rustdfs/namenode.log"

[data-node]
data-dir = "/var/lib/rustdfs/data"
log-file = "/var/log/rustdfs/datanode.log"
