name: checks
run-name: checks
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: rustfmt
        uses: ./.github/workflows/build-action
        with:
          command: | 
            `ls -a`
